!!at.knowcenter.sc.recomm.common.profiles.HybridRoundRobinWeightedSumProfile
recommType: items
profileNames:
  - trusts_mvp3_application_to_service_cb
  - trusts_mvp3_application_to_service_mp
profileWeights:
- 3
- 1