!!at.knowcenter.sc.recomm.common.profiles.HybridRoundRobinWeightedSumProfile
recommType: items
profileNames:
  - trusts_mvp3_dataset_to_application_cb
  - trusts_mvp3_dataset_to_application_mp
profileWeights:
- 3
- 1