version: '3.5'

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:
  solr_data:
  dsc_storage: {}
  recomm-solr-data:
  dataspaceconnector-data:

services:

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 8181:5432
    # env_file:
    #   - ./postgres/postgres.env
    environment:
      - POSTGRES_USER=${LOCAL_DSC_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${LOCAL_DSC_POSTGRES_PASSWORD}
      - POSTGRES_DB=${LOCAL_DSC_POSTGRES_DB}
    networks:
      - internal-net
      - ids-wide
    volumes:
      - dataspaceconnector-data:/var/lib/postgresql/data


  local-ckan:
    image: trusts/ckan:latest
    links:
      - db
      - solr
      - redis
      - dsc
    depends_on:
      - db
      - dsc
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_SITE_ID=${CKAN_SITE_ID}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - CKAN_SITE_TITLE=${CKAN_SITE_TITLE}
      - LOCAL_DATASPACE_CONNECTOR_URL=http://${LOCAL_NODE_NAME}
      - LOCAL_DATASPACE_CONNECTOR_PORT=8282
      - LOCAL_DATASPACE_CONNECTOR_USERNAME=${LOCAL_DATASPACE_CONNECTOR_USERNAME}
      - LOCAL_DATASPACE_CONNECTOR_PASSWORD=${LOCAL_DATASPACE_CONNECTOR_PASSWORD}
      - CKAN_EXTRA_PLUGIN_LIST=,theme,vocabularies
      - TRUSTS_CENTRAL_BROKER_URL=${BROKER_URL}
      - LOCAL_NODE_NAME=${LOCAL_NODE_NAME}
      - CKAN_AUTH_CREATE_USER_VIA_WEB=${CKAN_AUTH_CREATE_USER_VIA_WEB}
      - SCHEMING_DATASET_SCHEMAS=file:///schemas/dataset.yml file:///schemas/service.yml file:///schemas/application.yml
      - LICENSES_GROUP_URL=file:///etc/ckan/licenses.json
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./../trustshosts:/etc/hosts
      - ./schemas:/schemas
      - ./licenses.json:/etc/ckan/licenses.json
      #- ${DEV_FOLDER_FOR_CKAN_EXTENSION}:/usr/local/lib/python3.7/site-packages/ckanext/ids
    networks:
      - internal-net

  db:
    image: trusts/ckan_db:mvp1
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "ckan" ]
    ports:
     - 5432:5432
    networks:
      - internal-net

  solr:
    image:  trusts/ckan_solr:mvp1
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    networks:
      - internal-net
    #ports:
    # - "8983:8983"

  redis:
    image: redis:latest
    networks:
      - internal-net

  dsc:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:8.0.2
    container_name : ${LOCAL_NODE_NAME}
    ports:
      - 8282:8080
    networks:
      ids-wide:
        aliases:
          - repository.aisec.fraunhofer.de
      internal-net:
        aliases:
          - repository.trusts.eu
    volumes:
      - ./../trustshosts:/etc/hosts
      - ./idscert/:/conf/
      - ./config.json:/config/config.json
      # - dsc_storage:/home/nonroot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${LOCAL_DSC_POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${LOCAL_DSC_POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${LOCAL_DSC_POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASEPLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SERVER_SSL_ENABLED=false
      - CONFIGURATION_PATH=/config/config.json
      - BOOTSTRAP_ENABLED=false

  note-service:
    container_name: note-service
    image: nfourlat/note-service:latest
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5055
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ../logs/:/root/logs/
      - ./appsettings.json:/app/appsettings.json
    ports:
      - "0.0.0.0:5055:5055"
    networks:
      - internal-net

networks:
  ids-wide:
    external:
      name: ids-wide

  internal-net:
    driver: bridge
